CATEGORY_MAP = {
  "united states postal service": "post_office",
  "united states post office": "post_office",
  "lowes": "home_repair",
  "shell": "convenience",
  "hertz": "car_rental",
  "winn dixie": "supermarket",
  "publix": "supermarket",
  "walgreens": "pharmacy",
  "chevron": "fuel",
  "chilis": "restaurant",
  "7 eleven": "fuel",
  "moes southwest grill": "fast_food",
  "target": "department_store",
  "subway": "fast_food",
  "mobil": "convenience",
  "mcdonalds": "fast_food",
  "burger king": "fast_food",
  "wendys": "fast_food",
  "walmart": "supermarket",
  "the home depot": "home_repair",
  "krispy kreme": "fast_food",
  "chase": "atm",
  "best buy": "electronics",
  "cvs pharmacy": "pharmacy",
  "cvs": "pharmacy",
  "murphy usa": "fuel",
  "redbox": "vending_machine",
  "bank of america": "atm",
  "panera bread": "fast_food",
  "starbucks": "cafe",
  "rbc": "bank",
  "applebees neighborhood grill bar": "restaurant",
  "marathon": "fuel",
  "dennys": "restaurant",
  "wells fargo": "atm",
  "olive garden": "restaurant",
  "bmw": "car",
  "audi;mercedes benz;porsche": "car",
  "volkswagen": "car",
  "buca di beppo": "restaurant",
  "millers ale house": "restaurant",
  "jcpenney": "department_store",
  "sears": "department_store",
  "hm": "clothes",
  "speedway": "fuel",
  "kia": "car",
  "advance auto parts": "car_parts",
  "suntrust": "bank",
  "dominos": "fast_food",
  "kfc": "fast_food",
  "dunkin": "fast_food",
  "pizza hut": "restaurant",
  "bp shop": "convenience",
  "bp": "fuel",
  "chipotle": "fast_food",
  "kohls": "department_store",
  "five guys": "fast_food",
  "the melting pot": "restaurant",
  "cold stone creamery": "ice_cream",
  "bed bath beyond": "houseware",
  "belk": "department_store",
  "world market": "interior_decoration",
  "michaels": "craft",
  "books a million": "books",
  "mens wearhouse": "clothes",
  "verizon": "mobile_phone",
  "mattress firm": "bed",
  "dollar tree": "variety_store",
  "petco": "pet",
  "ross": "department_store",
  "hobby lobby": "craft",
  "waffle house": "restaurant",
  "outback steakhouse": "restaurant",
  "nuance": "gift",
  "inmotion": "electronics",
  "firehouse subs": "fast_food",
  "unos": "restaurant",
  "bob evans": "restaurant",
  "ihop": "restaurant",
  "perkins": "restaurant",
  "tropical smoothie cafe": "fast_food",
  "tijuana flats": "restaurant",
  "panda express": "fast_food",
  "jimmy johns": "fast_food",
  "staples": "stationery",
  "boston market": "fast_food",
  "hungry howies": "fast_food",
  "pep boys": "car_repair",
  "pnc bank": "atm",
  "ford": "car",
  "petsmart": "pet",
  "chick fil a": "fast_food",
  "regions bank": "bank",
  "sonnys bbq": "restaurant",
  "circle k": "fuel",
  "menchies": "ice_cream",
  "citgo": "fuel",
  "jasons deli": "restaurant",
  "popeyes": "fast_food",
  "red lobster": "restaurant",
  "cadillac": "car",
  "macys": "department_store",
  "dunkin donuts": "fast_food",
  "bealls": "department_store",
  "buffalo wings rings": "restaurant",
  "sally beauty": "hairdresser_supply",
  "great clips": "hairdresser",
  "marcos pizza": "restaurant",
  "gamestop": "video_games",
  "dollar general": "variety_store",
  "papa johns": "fast_food",
  "taco bell": "fast_food",
  "att": "mobile_phone",
  "family dollar": "variety_store",
  "china wok": "fast_food",
  "save a lot": "supermarket",
  "big lots": "department_store",
  "radioshack": "electronics",
  "tj maxx": "department_store",
  "dero": "bicycle_repair_station",
  "state farm": "insurance",
  "kangaroo express": "fuel",
  "dillards": "department_store",
  "dairy queen": "fast_food",
  "supercuts": "hairdresser",
  "planet fitness": "gym",
  "chargepoint": "charging_station",
  "tesla supercharger": "charging_station",
  "tires plus": "car",
  "hr block": "finance",
  "td bank": "bank",
  "texas roadhouse": "restaurant",
  "bbt": "bank",
  "racetrac": "fuel",
  "dicks sporting goods": "sports",
  "wawa": "fuel",
  "auntie annes": "fast_food",
  "office depot": "stationery",
  "hallmark": "gift",
  "gnc": "nutrition_supplements",
  "metro by t mobile": "mobile_phone",
  "little caesars": "fast_food",
  "ups": "post_box",
  "cheddars": "restaurant",
  "the salvation army": "charity",
  "party city": "party",
  "joann fabrics and crafts": "craft",
  "td ameritrade": "finance",
  "jenny craig": "healthcare",
  "t mobile": "mobile_phone",
  "academy sports outdoors": "sports",
  "aldi": "supermarket",
  "barnes noble": "books",
  "subaru": "car",
  "alamo": "car_rental",
  "autozone": "car_parts",
  "pet supermarket": "pet",
  "sunoco": "fuel",
  "truist": "bank",
  "marshalls": "department_store",
  "five below": "variety_store",
  "ulta beauty": "cosmetics",
  "chuck e cheeses": "restaurant",
  "rooms to go": "furniture",
  "shoe carnival": "shoes",
  "on the border": "restaurant",
  "the vitamin shoppe": "nutrition_supplements",
  "victorias secret": "clothes",
  "american eagle outfitters": "clothes",
  "foot locker": "shoes",
  "manchu wok": "fast_food",
  "qdoba": "fast_food",
  "hudson": "convenience",
  "ruby tuesday": "restaurant",
  "goodwill": "charity",
  "sams club": "supermarket",
  "volvo": "car",
  "hair cuttery": "hairdresser",
  "batteries plus bulbs": "electronics",
  "sonic": "fast_food",
  "spectrum": "telecommunication",
  "carrabbas italian grill": "restaurant",
  "dodge": "car",
  "chrysler": "car",
  "fiat": "car",
  "mobil mart": "convenience",
  "homegoods": "houseware",
  "the ups store": "copyshop",
  "massage envy": "massage",
  "play it again sports": "sports",
  "boost mobile": "mobile_phone",
  "u haul": "rental",
  "hilton": "hotel",
  "harbor freight tools": "hardware",
  "aspen dental": "dentist",
  "hyundai": "car",
  "amscot": "money_lender",
  "coinstar": "payment_terminal",
  "sherwin williams": "paint",
  "burgerfi": "fast_food",
  "einstein bros bagels": "fast_food",
  "woodspring suites": "hotel",
  "budget": "car_rental",
  "enterprise": "car_rental",
  "national": "car_rental",
  "ben jerrys": "ice_cream",
  "old navy": "clothes",
  "sprint": "mobile_phone",
  "exxon": "fuel",
  "kay jewelers": "jewelry",
  "sport clips": "hairdresser",
  "culvers": "fast_food",
  "safelite autoglass": "car_repair",
  "progressive": "insurance",
  "friendlys": "restaurant",
  "davids bridal": "clothes",
  "fedex office": "copyshop",
  "shake shack": "fast_food",
  "jersey mikes subs": "fast_food",
  "the fresh market": "supermarket",
  "leslies pool supplies": "swimming_pool",
  "cumberland farms": "fuel",
  "cnn newsstand": "newsagent",
  "avis": "car_rental",
  "labcorp": "healthcare",
  "express oil change tire engineers": "tyres",
  "public storage": "storage_rental",
  "bjs wholesale club": "wholesale",
  "carmax": "car",
  "golden corral": "restaurant",
  "hand stone massage and facial spa": "massage",
  "red wing": "shoes",
  "long john silvers": "fast_food",
  "advance america": "money_lender",
  "cricket wireless": "mobile_phone",
  "krispy krunchy chicken": "fast_food",
  "pepsi": "vending_machine",
  "edward jones": "finance",
  "check n go": "money_lender",
  "liberty tax": "finance",
  "re/max": "realty",
  "cosmoprof": "hairdresser_supply",
  "dasani": "vending_machine",
  "ubreakifix": "electronics",
  "nationwide": "insurance",
  "first watch": "restaurant",
  "cinnabon": "fast_food",
  "camping world": "caravan",
  "nissan": "car",
  "toyota": "car",
  "urban air": "fun",
  "sbarro": "fast_food",
  "nathans": "fast_food",
  "valvoline": "car_repair",
  "firestone": "car_repair",
  "tractor supply company": "country_store",
  "ace hardware": "home_repair",
  "habitat for humanity restore": "charity",
  "midas": "car_repair",
  "holiday inn express suites": "hotel",
  "flixbus": "car",
  "blaze pizza": "restaurant",
  "harley davidson": "motorcycle",
  "buffalo wild wings": "restaurant",
  "hometown news": "vending_machine",
  "caterpillar": "trade",
  "old time pottery": "houseware",
  "life storage": "storage_rental",
  "wingstreet": "fast_food",
  "anytime fitness": "gym",
  "oreilly auto parts": "car_parts",
  "petland": "pet",
  "kumon": "education",
  "nike": "clothes",
  "chicos": "clothes",
  "izod": "clothes",
  "van heusen": "clothes",
  "polo ralph lauren": "clothes",
  "tommy hilfiger": "clothes",
  "jcrew": "clothes",
  "white house black market": "clothes",
  "ann taylor": "clothes",
  "calvin klein": "clothes",
  "coach": "bag",
  "brooks brothers": "clothes",
  "perfumania": "perfumery",
  "restoration hardware": "furniture",
  "levis": "clothes",
  "jockey": "clothes",
  "williams sonoma": "houseware",
  "bose": "hifi",
  "gymboree": "clothes",
  "banana republic": "clothes",
  "columbia": "clothes",
  "lids": "clothes",
  "lane bryant": "clothes",
  "the childrens place": "clothes",
  "justice": "clothes",
  "samsonite": "bag",
  "carters": "clothes",
  "bonworth": "clothes",
  "christopher banks": "clothes",
  "kitchen collection": "houseware",
  "clarks": "shoes",
  "dxl mens apparel": "clothes",
  "sunglass hut": "optician",
  "crocs": "shoes",
  "gap": "clothes",
  "famous footwear": "shoes",
  "adidas": "sports",
  "reebok": "clothes",
  "loft": "clothes",
  "burlington": "department_store",
  "zaxbys": "fast_food",
  "cracker barrel": "restaurant",
  "uniqlo": "clothes",
  "cicis": "restaurant",
  "meson sandwiches": "fast_food",
  "napa auto parts": "car_parts",
  "jiffy lube": "car_repair",
  "aamco": "car_repair",
  "sleep number": "bed",
  "club pilates": "gym",
  "bath body works": "cosmetics",
  "kirklands": "interior_decoration",
  "talbots": "clothes",
  "claires": "fashion_accessories",
  "merle norman cosmetics": "cosmetics",
  "european wax center": "beauty",
  "bonefish grill": "restaurant",
  "pearle vision": "optician",
  "del taco": "fast_food",
  "acura": "car",
  "goodyear": "car_repair",
  "aarons": "furniture",
  "rent a center": "furniture",
  "chevrolet": "car",
  "amazon hub": "parcel_locker",
  "hibbett sports": "sports",
  "fantastic sams": "hairdresser",
  "smoothie king": "fast_food",
  "smashburger": "fast_food",
  "mathnasium": "prep_school",
  "crunch fitness": "gym",
  "benjamin moore": "paint",
  "storeright self storage": "storage_rental",
  "vans": "shoes",
  "nestle toll house cafe": "fast_food",
  "tillys": "clothes",
  "express": "clothes",
  "cotton on": "clothes",
  "hollister": "clothes",
  "fossil": "watches",
  "charleys philly steaks": "fast_food",
  "aw": "fast_food",
  "yankee candle": "candles",
  "boxlunch": "gift",
  "intimissimi": "clothes",
  "calzedonia": "clothes",
  "pandora": "jewelry",
  "the body shop": "cosmetics",
  "journeys": "shoes",
  "footaction": "shoes",
  "champs sports": "sports",
  "mac cosmetics": "cosmetics",
  "things remembered": "gift",
  "aerie": "clothes",
  "torrid": "clothes",
  "garage": "clothes",
  "hot topic": "clothes",
  "forever 21": "clothes",
  "zara": "clothes",
  "american girl": "toys",
  "spencer gifts": "gift",
  "lenscrafters": "optician",
  "zumiez": "clothes",
  "guess": "clothes",
  "pink": "clothes",
  "zales": "jewelry",
  "lush": "cosmetics",
  "buckle": "clothes",
  "disney store": "gift",
  "tous": "jewelry",
  "bareminerals": "cosmetics",
  "swarovski": "jewelry",
  "morphe": "cosmetics",
  "aldo": "shoes",
  "apple store": "electronics",
  "sephora": "cosmetics",
  "helzberg diamonds": "jewelry",
  "casper": "bed",
  "charlotte russe": "clothes",
  "tesla": "car",
  "brighton collectibles": "fashion_accessories",
  "michael kors": "clothes",
  "oakley": "optician",
  "pacsun": "clothes",
  "skechers": "shoes",
  "windsor": "clothes",
  "lovisa": "jewelry",
  "shoe palace": "shoes",
  "aeropostale": "clothes",
  "abercrombie kids": "clothes",
  "build a bear workshop": "toys",
  "fedex": "post_box",
  "american automobile association": "car",
  "edible arrangements": "gift",
  "quest diagnostics": "healthcare",
  "bravo": "supermarket",
  "lego": "vending_machine",
  "true value": "hardware",
  "dollar": "car_rental",
  "hudson news": "newsagent",
  "longhorn steakhouse": "restaurant",
  "hooters": "restaurant",
  "chuys": "restaurant",
  "la quinta inn": "hotel",
  "morgan morgan": "lawyer",
  "lululemon": "clothes",
  "nothing bundt cakes": "pastry",
  "clipper creek": "charging_station",
  "checkers": "fast_food",
  "centennial bank": "bank",
  "orangetheory fitness": "gym",
  "pollo tropical": "fast_food",
  "crumbl cookies": "pastry",
  "home2 suites by hilton": "hotel",
  "best western": "hotel",
  "hampton": "hotel",
  "amoco": "fuel",
  "arbys": "fast_food",
  "texaco": "fuel",
  "ymca": "gym",
  "krystal": "fast_food",
  "brusters ice cream": "ice_cream",
  "village inn": "restaurant",
  "tuesday morning": "houseware",
  "wayback burgers": "fast_food",
  "rack room shoes": "shoes",
  "ramada": "hotel",
  "berkshire hathaway homeservices": "realty",
  "tesla, inc": "charging_station",
  "total wine": "alcohol",
  "officemax": "stationery",
  "sports authority": "sports",
  "west marine": "boat",
  "allpoint": "atm",
  "baskin robbins": "ice_cream",
  "twistee treat": "ice_cream",
  "valero": "fuel",
  "mcu": "boat",
  "mountain dew": "vending_machine",
  "havertys": "furniture",
  "guitar center": "musical_instrument",
  "kilwins": "confectionery",
  "la fitness": "gym",
  "amc": "cinema",
  "bright horizons": "kindergarten",
  "sixt": "car_rental",
  "pei wei": "restaurant",
  "quiznos": "fast_food",
  "anthonys coal fired pizza": "restaurant",
  "allstate": "insurance",
  "24 hour fitness": "gym",
  "citibank": "atm",
  "yogurtland": "ice_cream",
  "dave busters": "restaurant",
  "whole foods market": "supermarket",
  "audi": "car",
  "pdq": "fast_food",
  "trader joes": "supermarket",
  "costco gasoline": "fuel",
  "bmw;mini": "car",
  "haagen dazs": "ice_cream",
  "mitsubishi": "car",
  "suzuki": "car",
  "ruths chris steak house": "restaurant",
  "infiniti": "car",
  "lexus": "car",
  "mercedes benz": "car",
  "rainbow": "clothes",
  "city national bank": "bank",
  "liberty": "fuel",
  "david yurman": "jewelry",
  "bloomingdales": "department_store",
  "honda": "car",
  "gulf": "fuel",
  "porsche": "car",
  "land rover": "car",
  "bankunited": "bank",
  "amtrust bank": "bank",
  "mazda": "car",
  "jamba": "fast_food",
  "del friscos double eagle steakhouse": "restaurant",
  "jaguar": "car",
  "retro fitness": "gym",
  "hsbc": "bank",
  "ethan allen": "furniture",
  "everbank": "bank",
  "stonegate bank": "bank",
  "pieology pizzeria": "restaurant",
  "safeway": "supermarket",
  "jamba juice": "fast_food",
  "jared": "jewelry",
  "pf changs": "restaurant",
  "prada": "clothes",
  "rainforest cafe": "restaurant",
  "the cheesecake factory": "restaurant",
  "california pizza kitchen": "restaurant",
  "nordstrom": "department_store",
  "yard house": "restaurant",
  "ashley homestore": "furniture",
  "western union": "money_transfer",
  "little free library": "public_bookcase",
  "warhammer": "games",
  "wingstop": "fast_food",
  "ideal food basket": "supermarket",
  "patel brothers": "supermarket",
  "under armour": "clothes",
  "dq grill chill": "fast_food",
  "brio": "restaurant",
  "charles schwab": "finance",
  "escapology": "fun",
  "desigual": "clothes",
  "the container store": "houseware",
  "neiman marcus": "department_store",
  "saks fifth avenue": "department_store",
  "americas best contacts eyeglasses": "optician",
  "lucky": "supermarket",
  "jets pizza": "restaurant",
  "extra space storage": "storage_rental",
  "usps": "post_box",
  "billabong": "clothes",
  "coco": "cafe",
  "cubesmart": "storage_rental",
  "steak n shake": "fast_food",
  "md now urgent care": "clinic",
  "eggersmann, schmalenbach, wolf, miele, gaggenau, kff, sophisticated living, subzero , the galley, shakuff, dornbracht, asco, cove, mgs": "cabinet_store",
  "coldwell banker": "realty",
  "sarpinos pizzeria": "fast_food",
  "amazing lash studio": "beauty",
  "dsw": "shoes",
  "xfinity": "telecommunication",
  "sprouts farmers market": "supermarket",
  "playa bowls": "fast_food",
  "kung fu tea": "cafe",
  "the brass tap": "pub",
  "cookies by design": "pastry",
  "key food": "supermarket",
  "rei": "outdoor",
  "lamborghini": "car",
  "la petite academy": "kindergarten",
  "kindercare": "kindergarten",
  "tutor time": "kindergarten",
  "tgi fridays": "restaurant",
  "nike factory store": "clothes",
  "saks off 5th": "department_store",
  "bass pro shops": "outdoor",
  "bubba gump shrimp company": "restaurant",
  "ale house": "restaurant",
  "kwik shop": "convenience",
  "the original pancake house": "restaurant",
  "kmart": "department_store",
  "au bon pain": "fast_food",
  "fuddruckers": "restaurant",
  "nordstrom rack": "clothes",
  "rubios": "fast_food",
  "west elm": "furniture",
  "ducati": "motorcycle",
  "pinkberry": "ice_cream",
  "golf galaxy": "sports",
  "ra sushi": "restaurant",
  "yogen fr\u00fcz": "ice_cream",
  "vespa": "motorcycle",
  "canam;seadoo;star;yamaha;zero": "motorsports",
  "cycle gear": "motorcycle",
  "segafredo": "cafe",
  "century 21": "relaty",
  "urban outfitters": "clothes",
  "kiko milano": "cosmetics",
  "diesel": "clothes",
  "havaianas": "shoes",
  "armani exchange": "clothes",
  "xot": "shoes",
  "live!": "clothes",
  "steve madden": "shoes",
  "ted baker": "clothes",
  "nespresso": "coffee",
  "zadig voltaire": "clothes",
  "lacoste": "clothes",
  "7 for all mankind": "clothes",
  "freddy": "clothes",
  "allsaints": "clothes",
  "scotch soda": "clothes",
  "paul": "bakery",
  "superdry": "clothes",
  "johnston murphy": "shoes",
  "vapiano": "restaurant",
  "ktm;kawasaki,suzuki;husqvarna": "motorcycle",
  "puma": "clothes",
  "oshkosh bgosh": "clothes",
  "kona grill": "restaurant",
  "dkny": "clothes",
  "fitness first": "gym",
  "eaglerider": "motorcycle_rental",
  "westar": "fuel",
  "motherhood maternity": "clothes",
  "juan valdez caf\u00e9": "coffee",
  "best buy mobile": "mobile_phone",
  "round table pizza": "restaurant",
  "banco do brasil": "bank",
  "pottery barn": "furniture",
  "the webster": "clothes",
  "equinox": "gym",
  "citi bike": "bicycle_rental",
  "davita dialysis": "clinic",
  "aroma espresso bar": "cafe",
  "freshii": "restaurant",
  "joe the juice": "cafe",
  "thrifty": "car",
  "drybar": "hairdresser",
  "the habit burger grill": "fast_food",
  "best buy express": "electronics",
  "ocean bank": "bank",
  "synovus": "bank",
  "alfa romeo": "car",
  "sub zero": "ice_cream",
  "fastenal": "trade",
  "i heart mac cheese": "restaurant",
  "converse": "shoes",
  "vca animal hospital": "veterinary",
  "postalannex": "post_office",
  "cava": "restaurant",
  "vice city shops": "tobacco",
  "stanton optical": "optician",
  "tag heuer": "watches",
  "giorgio armani": "clothes",
  "maison margiela": "clothes",
  "warby parker": "optician",
  "bash": "clothes",
  "omega": "watches",
  "saint laurent": "clothes",
  "thom browne": "clothes",
  "alice olivia": "clothes",
  "bulthaup": "kitchen",
  "louis vuitton": "clothes",
  "tory burch": "clothes",
  "marc jacobs": "clothes",
  "givenchy": "clothes",
  "gucci": "clothes",
  "rimowa": "bag",
  "oliver peoples": "optician",
  "the shade store": "window_blind",
  "fendi": "clothes",
  "alexander mcqueen": "clothes",
  "balenciaga": "clothes",
  "cartier": "jewelry",
  "valentino": "clothes",
  "herm\u00e8s": "clothes",
  "salvatore ferragamo": "shoes",
  "blink": "charging_station",
  "tiger mart": "convenience",
  "24 hour fitness;subway": "fast_food",
  "microsoft store": "electronics",
  "burberry": "clothes",
  "hugo boss": "clothes",
  "anthropologie": "clothes",
  "na hoku": "jewelry",
  "maje": "clothes",
  "abercrombie fitch": "clothes",
  "ugg": "shoes",
  "johnny rockets": "restaurant",
  "cinepolis": "cinema",
  "landmark theatres": "cinema",
  "mod pizza": "fast_food",
  "suitsupply": "clothes",
  "bluemercury": "cosmetics",
  "solstice sunglasses": "optician",
  "tumi": "bag",
  "madewell": "clothes",
  "alex and ani": "jewelry",
  "swatch": "watches",
  "iberia": "bank",
  "costco": "wholesale",
  "laser": "travel_agency",
  "my eyelab": "optician",
  "pollo campero": "fast_food",
  "eutelsat": "utilities",
  "dryclean usa": "dry_cleaning",
  "tcby": "ice_cream",
  "visionworks": "optician",
  "benihana": "restaurant",
  "kellys cajun grill": "fast_food",
  "icing": "jewelry",
  "urban move": "clothes",
  "dior": "clothes",
  "ermenegildo zegna": "clothes",
  "versace": "clothes",
  "tiffany company": "jewelry",
  "christian louboutin": "shoes",
  "panerai": "watches",
  "a lange s\u00f6hne": "watches",
  "poltrona frau": "furniture",
  "bulgari": "fashion_accessories",
  "vacheron constantin": "watches",
  "iwc": "watches",
  "kartell": "furniture",
  "tods": "shoes",
  "rolex": "watches",
  "rapha": "sports",
  "cos": "clothes",
  "seiko": "watches",
  "loro piana": "clothes",
  "dolce gabbana": "clothes",
  "aesop": "cosmetics",
  "ligne roset": "furniture",
  "design within reach": "furniture",
  "pet food express": "pet",
  "carvel": "ice_cream",
  "freeway insurance": "insurance",
  "life time": "gym",
  "curio collection": "hotel",
  "poupette st barth": "clothes",
  "chanel": "clothes",
  "hyatt centric": "hotel",
  "kimpton": "hotel",
  "jw marriott": "hotel",
  "libertyx": "atm",
  "everything but water": "clothes",
  "tommy bahama": "clothes",
  "free people": "clothes",
  "naturalizer": "shoes",
  "montblanc": "fashion_accessories",
  "psycho bunny": "clothes",
  "fabletics": "clothes",
  "lucky brand": "clothes",
  "mango": "clothes",
  "house of hoops": "shoes",
  "stuart weitzman": "shoes",
  "cohens fashion optical": "optician",
  "shell shop": "convenience",
  "yotel": "hotel",
  "aveda": "cosmetics",
  "ruta 75": "restaurant",
  "dtlr": "shoes",
  "banfield pet hospital": "veterinary",
  "trek": "bicycle",
  "onemain financial": "finance",
  "convenient food mart": "convenience",
  "reddy ice": "vending_machine",
  "amerigas": "vending_machine",
  "kiehls": "cosmetics",
  "earls": "restaurant",
  "moneygram": "money_transfer",
  "jo malone": "perfumery",
  "bally": "shoes",
  "agent provocateur": "clothes",
  "diptyque": "perfumery",
  "porsche design": "fashion_accessories",
  "sur la table": "houseware",
  "sweetgreen": "fast_food",
  "days inn": "hotel",
  "thumbs up!": "fuel",
  "tommy hilfiger kids": "clothes",
  "nautica": "clothes",
  "dds discounts": "department_store",
  "fastsigns": "signs",
  "estrella insurance": "insurance",
  "regal cinemas": "cinema",
  "finish line": "sports",
  "citi trends": "clothes",
  "mobilezone": "mobile_phone",
  "south state bank": "bank",
  "city": "atm",
  "blue rhino": "vending_machine",
  "golden krust caribbean bakery grill": "fast_food",
  "evgo dc": "charging_station",
  "sweetfrog": "ice_cream",
  "maple street biscuit company": "restaurant",
  "ace cash express": "money_lender",
  "health mart": "pharmacy",
  "teds montana grill": "restaurant",
  "zo\u00ebs kitchen": "fast_food",
  "navy federal credit union": "bank",
  "true religion": "clothes",
  "athleta": "clothes",
  "soma": "clothes",
  "jjill": "clothes",
  "jos a bank": "clothes",
  "loccitane": "cosmetics",
  "platos closet": "clothes",
  "jackson hewitt": "finance",
  "floor decor": "flooring",
  "pure barre": "gym",
  "ppg paints": "paint",
  "hardees": "fast_food",
  "pita pit": "fast_food",
  "tony romas": "restaurant",
  "community first credit union": "atm",
  "churchs chicken": "fast_food",
  "pilot": "fuel",
  "mission bbq": "restaurant",
  "copelands": "restaurant",
  "the keg": "restaurant",
  "buy buy baby": "baby_goods",
  "shell express": "fuel",
  "bonchon chicken": "restaurant",
  "yogurt mountain": "ice_cream",
  "chicken salad chick": "fast_food",
  "metro diner": "restaurant",
  "marble slab creamery": "ice_cream",
  "mellow mushroom": "restaurant",
  "vision express": "optician",
  "coopers hawk": "wine",
  "destination maternity": "clothes",
  "iga": "supermarket",
  "gate": "fuel",
  "sola salons": "beauty",
  "block advisors": "finance",
  "ikea": "fast_food",
  "ritas italian ice": "ice_cream",
  "farmers insurance": "insurance",
  "fye": "music",
  "sarku japan": "fast_food",
  "great american cookies": "fast_food",
  "new york company": "clothes",
  "fast fix": "jewelry",
  "minuteman press": "copyshop",
  "randstad": "recruiting",
  "jazzercise": "gym",
  "adam eve": "erotic",
  "evgo": "charging_station",
  "take 5 oil change": "car_repair",
  "bbva": "bank",
  "donatos pizza": "restaurant",
  "insomnia cookies": "pastry",
  "once upon a child": "clothes",
  "coffeeshop company": "cafe",
  "whataburger": "fast_food",
  "coca cola": "vending_machine",
  "chrysler, dodge, jeep, ram": "car",
  "uniform destination": "clothes",
  "american freight": "department_store",
  "the joint chiropractic": "healthcare",
  "cato": "clothes",
  "veterans of foreign wars of the united states": "social_centre",
  "esporta fitness": "gym",
  "cash america international": "pawnbroker",
  "star mart": "convenience",
  "red roof inn": "hotel",
  "boot barn": "clothes",
  "ollies bargain outlet": "variety_store",
  "peloton": "sports",
  "vineyard vines": "clothes",
  "kendra scott": "jewelry",
  "francescas": "clothes",
  "tempur pedic": "bed",
  "untuckit": "clothes",
  "bmo": "atm",
  "world gym": "gym",
  "wilsons leather": "clothes",
  "rue21": "clothes",
  "costa": "cafe",
  "honey baked ham": "fast_food",
  "asics": "shoes",
  "homewood suites": "hotel",
  "wild birds unlimited": "pet",
  "papa murphys": "fast_food",
  "f45 training": "gym",
  "84 lumber": "trade",
  "cost cutters": "hairdresser",
  "beef obradys": "restaurant",
  "duck donuts": "fast_food",
  "cell phone repair": "electronics",
  "brueggers bagels": "fast_food",
  "city gear": "clothes",
  "avon": "cosmetics",
  "smallcakes": "pastry",
  "warhorse": "bar",
  "total": "fuel",
  "robeks": "fast_food",
  "which wich?": "fast_food",
  "regus": "office",
  "sky zone": "fun",
  "tazikis mediterranean cafe": "fast_food",
  "hotworx": "gym",
  "presto": "atm",
  "geico": "insurance",
  "metronet": "telecommunication",
  "gaines street pies": "restaurant",
  "monster energy": "vending_machine",
  "powerade": "vending_machine",
  "golds gym": "gym",
  "its fashion": "clothes",
  "n\u00e9kter juice bar": "fast_food",
  "piggly wiggly": "supermarket",
  "electrify america": "charging_station",
  "ww studio": "religion",
  "ac hotel": "hotel",
  "regal nails": "beauty",
  "drivetime": "car",
  "comfort inn suites": "hotel",
  "florida blue": "insurance",
  "pro nails": "beauty",
  "little free pantry": "food_sharing",
  "chrysler;dodge;fiat;jeep;ram": "car",
  "mcalisters deli": "restaurant",
  "penske truck rental": "rental",
  "sunbelt rentals": "rental",
  "keller williams realty": "realty",
  "club champion": "sports",
  "pet supplies plus": "pet",
  "romanos macaroni grill": "restaurant",
  "baja fresh": "fast_food",
  "comerica bank": "bank",
  "planet smoothie": "cafe",
  "7 11": "fuel",
  "dickeys barbecue pit": "restaurant",
  "edys": "fast_food",
  "edwin watts golf shops": "variety_store",
  "twin peaks": "restaurant",
  "sony": "electronics",
  "ocharleys": "restaurant",
  "cheeburger cheeburger": "restaurant",
  "red robin": "restaurant",
  "fidelity bank": "bank",
  "jo ann": "craft",
  "epic wings n things": "fast_food",
  "marriott": "hotel",
  "paul mitchell": "hairdresser",
  "fifth third bank": "atm",
  "clean juice": "fast_food",
  "bambu": "cafe",
  "the north face": "clothes",
  "home2 suites by hilton;hilton garden inn": "hotel",
  "voodoo doughnut": "fast_food",
  "us polo assn": "clothes",
  "new balance": "shoes",
  "barbershop": "hairdresser",
  "abbotts frozen custard": "ice_cream",
  "international alliance of theatrical stage employees": "social_centre",
  "transportation communication union": "social_centre",
  "vitamin world": "nutrition_supplements",
  "le creuset": "houseware",
  "timberland": "clothes",
  "cole haan": "shoes",
  "kate spade new york": "clothes",
  "robert graham": "clothes",
  "vera bradley": "bag",
  "lindt": "chocolate",
  "janie jack": "clothes",
  "cafe rio": "restaurant",
  "noodles company": "restaurant",
  "freddys": "fast_food",
  "massage therapy,sound healing,thai massage": "healthcare",
  "amazon hub locker": "parcel_locker",
  "seasons 52": "restaurant",
  "regis": "hairdresser",
  "white castle": "fast_food",
  "payless shoesource": "shoes",
  "movado": "watches",
  "kipling": "bag",
  "wetzels pretzels": "fast_food",
  "dooney bourke": "fashion_accessories",
  "quiksilver": "clothes",
  "perry ellis": "clothes",
  "volcom": "clothes",
  "champion": "clothes",
  "simply mac": "electronics",
  "oneill": "clothes",
  "hurley": "clothes",
  "hanesbrands": "clothes",
  "carhartt": "clothes",
  "izod;van heusen": "clothes",
  "itsugar": "confectionery",
  "alamo drafthouse cinema": "cinema",
  "embassy suites": "hotel",
  "school of rock": "music_school",
  "mister car wash": "car_wash",
  "teriyaki madness": "fast_food",
  "ding tea": "cafe",
  "zero degrees": "fast_food",
  "foxtail coffee": "cafe",
  "matcha cafe maiko": "cafe",
  "jinya ramen bar": "restaurant",
  "mini melts": "vending_machine",
  "christian science reading room": "books",
  "raceway": "fuel",
  "quality inn": "hotel",
  "mapfre": "insurance",
  "tuffy": "car_repair",
  "bahama breeze": "restaurant",
  "andys frozen custard": "ice_cream",
  "maurices": "clothes",
  "sears auto center": "car_repair",
  "mail boxes etc": "post_office",
  "avalon": "clothes",
  "quick tag": "vending_machine",
  "davi nails": "beauty",
  "the goddard school": "kindergarten",
  "sizzler": "restaurant",
  "ponderosa steakhouse": "restaurant",
  "joes crab shack": "restaurant",
  "house of blues": "restaurant",
  "target optical": "optician",
  "worldmark orlando reunion": "hotel",
  "origins": "cosmetics",
  "johnny was": "clothes",
  "sperry": "shoes",
  "eddie bauer": "clothes",
  "max mara": "clothes",
  "puma outlet": "clothes",
  "ecco": "shoes",
  "humana": "charity",
  "altitude": "fun",
  "diamond resorts": "hotel",
  "beer, sodas, juice, drinks, chips, snacks, tobaco": "beverages",
  "brunello cucinelli": "clothes",
  "jimmy choo": "shoes",
  "maidenform": "clothes",
  "portillos": "fast_food",
  "hess": "fuel",
  "allegro one box": "parcel_locker",
  "motel 6": "hotel",
  "amazon locker": "parcel_locker",
  "kfc;taco bell": "fast_food",
  "golinski tax advisors": "finance",
  "va": "social_facility",
  "boys girls club": "social_facility",
  "united community bank": "atm",
  "victra": "mobile_phone",
  "loving hut": "restaurant",
  "curves": "gym",
  "fresenius medical care": "clinic",
  "carquest": "car_parts",
  "sylvan": "prep_school",
  "dero fixit": "bicycle_repair_station",
  "checksmart": "money_lender",
  "dimmitt": "car",
  "bright now! dental": "dentist",
  "bjs": "restaurant",
  "meineke": "car_repair",
  "sam ash": "music",
  "dero fixit station": "bicycle_repair_station",
  "skyline chili": "restaurant",
  "toni guy": "hairdresser",
  "suki hana": "fast_food",
  "chevrolet;chrysler;ford;honda;jeep;nissan": "car",
  "wasabi": "restaurant",
  "guidewell emergency doctors": "hospital",
  "doubletree": "hotel",
  "minuteclinic": "doctors",
  "kids r kids": "childcare",
  "the lash lounge": "beauty",
  "western dental": "dentist",
  "ram": "car",
  "jeep": "car",
  "buick": "car",
  "gmc": "car",
  "counterculture coffee": "cafe",
  "elevenses co": "bakery",
  "blanchards coffee, bandit coffee, methodical coffee": "vending_machine",
  "made coffee": "cafe",
  "clean energy": "fuel",
  "m\u00dcv": "cannabis",
  "go games toys": "toys",
  "extended stay america": "hotel",
  "rural king": "country_store",
  "telefix": "electronics",
  "banter by piercing pagoda": "jewelry",
  "rocky mountain chocolate factory": "confectionery",
  "dogtopia": "animal_boarding",
  "blimpie": "fast_food",
  "dick norris": "car",
  "sushi yama": "restaurant",
  "manpower": "recruiting",
  "jacks": "fast_food",
  "american signature furniture": "furniture",
  "boars head": "deli",
  "catherines": "clothes",
  "bridgepoint church": "place_of_worship",
  "rituals": "cosmetics",
  "avenue": "clothes",
  "foot solutions": "shoes",
  "mercedes benz bmw": "car_repair",
  "alphagraphics": "copyshop",
  "thorntons": "fuel",
  "kahwa coffee": "cafe",
  "coyote ugly saloon": "bar",
  "snap fitness": "gym",
  "godfathers pizza": "restaurant",
  "vomfass": "deli",
  "suncost": "bank",
  "grid": "bicycle_rental",
  "republic bank": "bank",
  "planned parenthood": "clinic",
  "acceptance": "insurance",
  "element": "hairdresser",
  "aloft": "hotel",
  "miracle ear": "healthcare",
  "batdorf bronson": "cafe",
  "trillium": "fuel",
  "csl plasma": "healthcare",
  "foxtail": "cafe",
  "socratic solutions inc": "health_food",
  "grocery outlet": "supermarket",
  "earthwise pet": "pet",
  "bluepearl": "veterinary",
  "polestar": "car",
  "true food kitchen": "restaurant",
  "myeyedoctor": "healthcare",
  "madison reed": "beauty",
  "eaton": "charging_station",
  "hampton inn suites": "hotel",
  "fatburger": "fast_food",
  "corvette": "car",
  "nova charge": "charging_station",
  "wagamama": "restaurant",
  "imagine schools": "school",
  "american legion": "social_centre",
  "cat cloud": "cafe",
  "bandit_coffee;kuma_coffee": "cafe",
  "at home": "houseware",
  "curaleaf": "cannabis",
  "moneypoint": "atm",
  "amazon": "supermarket",
  "mint mobile": "mobile_phone",
  "mint": "mobile",
  "airbnb": "hotel",
  "amzn mktp": "supermarket",
  "crush xi": "restaurant",
  "abc fine winespirits": "alcohol",
  "umami": "resturant",
  "att payment": "internet",
  "mangetsu kbbq": "restaurant",
  "hell n blazes brewing": "alcohol",
  "iriashi japanese": "restaurant",
  "dusty joes smokin": "fast_food"
}

CITY_LIST_FL = ["Acacia Villas","Alachua","Alafaya","Alford","Allentown","Altamonte Springs","Altha","Altoona","Alturas","Alva",
"Andrews","Anna Maria","Apalachicola","Apollo Beach","Apopka","Arcadia","Archer","Aripeka","Asbury Lake","Astatula","Astor","Atlantic Beach",
"Atlantis","Auburndale","Aucilla","Avalon","Ave Maria","Aventura","Avon Park","Azalea Park","Babson Park","Bagdad","Bal Harbour village","Baldwin","Balm","Bardmoor",
"Bartow","Bascom","Bay Harbor Islands","Bay Hill","Bay Lake","Bay Pines","Bayonet Point","Bayport","Bayshore Gardens","Beacon Square","Bear Creek","Bee Ridge","Bell",
"Bellair-Meadowbrook Terrace","Belle Glade","Belle Isle","Belleair Beach","Belleair Bluffs","Belleair Shore","Belleair","Belleview","Bellview","Berkshire Lakes",
"Berrydale","Beverly Beach","Beverly Hills","Big Coppitt Key","Big Pine Key","Biscayne Park village","Bithlo","Black Diamond","Black Hammock","Bloomingdale","Blountstown","Boca Raton",
"Bokeelia","Bonifay","Bonita Springs","Boulevard Gardens","Bowling Green","Boynton Beach","Bradenton Beach","Bradenton","Bradfordville","Bradley Junction","Brandon","Branford",
"Brent","Briny Breezes","Bristol","Broadview Park","Bronson","Brooker","Brookridge","Brooksville","Brownsdale","Brownsville","Buckhead Ridge","Buckingham","Buenaventura Lakes",
"Bunnell","Burnt Store Marina","Bushnell","Butler Beach","Cabana Colony","Callahan","Callaway","Campbell","Campbellton","Canal Point","Cape Canaveral","Cape Coral",
"Capitola","Captiva","Carrabelle","Carrollwood","Caryville","Casselberry","Cedar Grove","Cedar Key","Celebration","Center Hill","Century","Chaires","Charleston Park",
"Charlotte Harbor","Charlotte Park","Chattahoochee","Cheval","Chiefland","Chipley","Chokoloskee","Christmas","Chuluota","Chumuckla","Cinco Bayou","Citrus Hills","Citrus Park",
"Citrus Springs","Clarcona","Clearwater","Clermont","Cleveland","Clewiston","Cloud Lake","Cobbtown","Cocoa Beach","Cocoa West","Cocoa","Coconut Creek",
"Coleman","Combee Settlement","Connerton","Conway","Cooper","Coral Gables","Coral Springs","Coral Terrace","Cortez","Cottondale","Country Club","Country Walk",
"Crawfordville","Crescent Beach","Crescent","Crestview","Crooked Lake Park","Cross","Crystal Lake","Crystal River","Crystal Springs","Cudjoe Key",
"Cutler Bay","Cypress Gardens","Cypress Lake","Cypress Quarters","Dade North","Dade","Dania Beach","Davenport","Davie","Day","Daytona Beach Shores",
"Daytona Beach","De Leon Springs","DeBary","DeFuniak Springs","DeLand Southwest","DeLand","Deerfield Beach","Delray Beach","Deltona","Desoto Acres",
"Desoto Lakes","Destin","Dickerson","Dixonville","Doctor Phillips","Doral","Dover","Duck Key","Dundee","Dunedin","Dunnellon","Eagle Lake","East Bronson",
"East Lake","East Lake-Orient Park","East Milton","East Palatka","East Williston","Eastpoint","Eatonville","Ebro","Edgewater","Edgewood","Eglin AFB","Egypt Lake-Leto",
"El Portal village","Elfers","Ellenton","Englewood","Ensley","Estero village","Esto","Eustis","Everglades","Fairview Shores","Fanning Springs","Feather Sound","Fellsmere",
"Fern Park","Fernandina Beach","Ferndale","Ferry Pass","Fidelis","Fish Hawk","Fisher Island","Five Points","Flagler Beach","Flagler Estates","Fleming Island","Floral","Florida",
"Florida Gulf Coast University","Florida Ridge","Floridatown","Forest","Fort Braden","Fort Denaud","Fort Green","Fort Green Springs","Fort Lauderdale","Fort Meade","Fort Myers Beach",
"Fort Myers Shores","Fort Myers","Fort Pierce North","Fort Pierce South","Fort Pierce","Fort Walton Beach","Fort White","Fountainebleau","Four Corners","Franklin Park","Freeport",
"Frostproof","Fruit Cove","Fruitland Park","Fruitville","Fuller Heights","Fussels Corner","Gainesville","Garcon Point","Garden Grove","Gardner","Gateway","Geneva","Gibsonton","Gifford","Gladeview",
"Glen Ridge","Glen Saint Mary","Glencoe","Glenvar Heights","Golden Beach","Golden Gate","Golden Glades","Goldenrod","Golf village","Gonzalez","Goodland","Gotha","Goulding","Goulds","Graceville",
"Grand Ridge","Grant-Valkaria","Green Cove Springs","Greenacres","Greenbriar","Greensboro","Greenville","Greenwood","Grenelefe","Gretna","Grove","Groveland",
"Gulf Breeze","Gulf Gate","Gulf Stream","Gulfport","Gun Club Estates","Haines","Hallandale Beach","Hampton","Harbor Bluffs","Harbour Heights","Harlem","Harlem Heights",
"Harold","Hastings","Havana","Haverhill","Hawthorne","Heathrow","Heritage Bay","Heritage Pines","Hernando Beach","Hernando","Hialeah Gardens","Hialeah","High Point","High Springs",
"Highland Beach","Highland","Highland Park village","Hill n Dale","Hillcrest Heights","Hilliard","Hillsboro Beach","Hillsboro Pines","Hobe Sound","Holden Heights","Holiday","Holley",
"Holly Hill","Hollywood","Holmes Beach","Homeland","Homestead Base","Homestead","Homosassa","Homosassa Springs","Horizon West","Horseshoe Beach","Hosford","Howey-in-the-Hills","Hudson",
"Hunters Creek","Hurlburt Field","Hutchinson Island South","Hypoluxo","Immokalee","Indialantic","Indian Creek village","Indian Harbour Beach","Indian Lake Estates","Indian River Estates",
"Indian River Shores","Indian Rocks Beach","Indian Shores","Indiantown village","Inglis","Interlachen","Inverness Highlands North","Inverness Highlands South","Inverness","Inwood","Iona","Islamorada",
"Village of Islands village","Island Walk","Istachatta","Ives Estates","Jacksonville Beach","Jacksonville","Jacob","Jan Phyl Village","Jasmine Estates","Jasper","Jay","Jennings","Jensen Beach",
"June Park","Juno Beach","Juno Ridge","Jupiter Farms","Jupiter Inlet Colony","Jupiter Island","Jupiter","Kathleen","Kendale Lakes","Kendall","Kendall West","Kenneth","Kensington Park",
"Kenwood Estates","Key Biscayne village","Key Colony Beach","Key Largo","Key Vista","Key West","Keystone","Keystone Heights","Kissimmee","La Crosse","LaBelle","Lacoochee","Lady Lake",
"Laguna Beach","Lake Alfred","Lake Belvedere Estates","Lake Buena Vista","Lake Butler","Lake Butler","Lake","Lake Clarke Shores","Lake Hamilton","Lake Harbor","Lake Hart","Lake Helen",
"Lake Kathryn","Lake Kerr","Lake Lindsey","Lake Lorraine","Lake Mack-Forest Hills","Lake Magdalene","Lake Mary Jane","Lake Mary","Lake Mystic","Lake Panasoffkee","Lake Park","Lake Placid","Lake Sarasota","Lake Wales",
"Lake Worth Beach","Lakeland Highlands","Lakeland","Lakeside","Lakewood Park","Lakewood Ranch","Lamont","Land O Lakes","Lantana","Largo","Lauderdale Lakes","Lauderdale-by-the-Sea","Lauderhill",
"Laurel","Laurel Hill","Lawtey","Layton","Lazy Lake village","Lealman","Lecanto","Lee","Leesburg","Lehigh Acres","Leisure","Lely","Lely Resort","Lemon Grove","Liberty Triangle","Lighthouse Point",
"Limestone","Limestone Creek","Lisbon","Live Oak","Lloyd","Lochmoor Waterway Estates","Lockhart","Longboat Key","Longwood","Loughman","Lower Grand Lagoon","Loxahatchee Groves","Lutz","Lynn Haven",
"Macclenny","Madeira Beach","Madison","Maitland","Malabar","Malone","Manalapan","Manasota Key","Manatee Road","Mango","Mangonia Park","Marathon","Marco Island","Marco Shores-Hammock Bay",
"Margate","Marianna","Marineland","Marion Oaks","Mary Esther","Masaryktown","Mascotte","Matlacha","Matlacha Isles-Matlacha Shores","Mayo","McGregor","McIntosh","Meadow Oaks","Meadow Woods",
"Medley","Medulla","Melbourne Beach","Melbourne Village","Melbourne","Memphis","Merritt Island","Mexico Beach","Miami Beach","Miami Gardens","Miami Lakes","Miami Shores village",
"Miami Springs","Miami","Micanopy","Micco","Miccosukee","Middleburg","Midway","Midway","Midway","Milton","Mims","Minneola","Miramar Beach","Miramar","Molino","Monticello","Montura",
"Montverde","Moon Lake","Moore Haven","Morriston","Mount Carmel","Mount Dora","Mount Plymouth","Mulat","Mulberry","Munson","Myrtle Grove","Naples Manor","Naples Park","Naples","Naranja",
"Nassau Village-Ratliff","Navarre Beach","Navarre","Neptune Beach","New Port Richey East","New Port Richey","New Smyrna Beach","Newberry","Niceville","Nobleton","Nocatee","Nokomis",
"Noma","North Bay Village","North Brooksville","North DeLand","North Fort Myers","North Key Largo","North Lauderdale","North Merritt Island","North Miami Beach","North Miami","North Palm Beach village",
"North Port","North Redington Beach","North River Shores","North Sarasota","North Weeki Wachee","Northdale","Oak Hill","Oak Ridge","Oakland Park","Oakland","Oakleaf Plantation","Ocala Estates",
"Ocala","Ocean Breeze","Ocean","Ocean Ridge","Ocklawaha","Ocoee","Odessa","Ojus","Okahumpka","Okeechobee","Old Miakka","Oldsmar","Olga","Olympia Heights","On Top of the World","Ona","Opa-locka",
"Orange","Orange Park","Orangetree","Orchid","Oriole Beach","Orlando","Orlovista","Ormond Beach","Ormond-by-the-Sea","Osprey","Otter Creek","Oviedo","Pace","Page Park","Pahokee","Paisley",
"Palatka","Palm Bay","Palm Beach Gardens","Palm Beach Shores","Palm Beach","Palm","Palm Coast","Palm Harbor","Palm River-Clair Mel","Palm Shores","Palm Springs North","Palm Springs village",
"Palm Valley","Palmer Ranch","Palmetto Bay village","Palmetto Estates","Palmetto","Palmona Park","Panacea","Panama Beach","Panama","Paradise Heights","Parker","Parkland","Pasadena Hills",
"Patrick AFB","Paxton","Pea Ridge","Pebble Creek","Pelican Bay","Pelican Marsh","Pembroke Park","Pembroke Pines","Penney Farms","Pensacola Station","Pensacola","Perry","Pierson",
"Pine Air","Pine Castle","Pine Hills","Pine Island","Pine Island Center","Pine Lakes","Pine Level","Pine Manor","Pine Ridge","Pine Ridge","Pinecraft","Pinecrest village","Pineland","Pinellas Park","Pinewood","Pioneer",
"Pittman","Plant","Plantation","Plantation Island","Plantation Mobile Home Park","Plantation","Poinciana","Point Baker","Polk","Pomona Park","Pompano Beach","Ponce Inlet","Ponce de Leon",
"Port Charlotte","Port LaBelle","Port Orange","Port Richey","Port Salerno","Port Saint Joe","Port Saint John","Port Saint Lucie","Pretty Bayou","Princeton","Progress Village","Punta Gorda","Punta Rassa",
"Quail Ridge","Quincy","Raiford","Rainbow Lakes Estates","Rainbow Park","Rainbow Springs","Raleigh","Reddick","Redington Beach","Redington Shores","Richmond Heights","Richmond West","Ridge Manor",
"Ridge Wood Heights","Ridgecrest","Rio","Rio Pinar","River Park","River Ridge","Riverview","Riviera Beach","Rockledge","Roeville","Roosevelt Gardens","Roseland","Rotonda","Royal Palm Beach village","Royal Palm Estates",
"Ruskin","Safety Harbor","Samoset","Samsula-Spruce Creek","San Antonio","San Carlos Park","San Castle","Sanford","Sanibel","Sarasota Springs","Sarasota","Satellite Beach","Sawgrass","Schall Circle",
"Scottsmoor","Sea Ranch Lakes village","Sebastian","Sebring","Seffner","Seminole Manor","Seminole","Seville","Sewalls Point","Shady Hills","Shalimar","Sharpes","Siesta Key","Silver Lake","Silver Springs",
"Silver Springs Shores","Silver Springs Shores East","Sky Lake","Sneads","Solana","Sopchoppy","Sorrento","South Apopka","South Bay","South Beach","South Bradenton","South Brooksville","South Daytona","South Gate Ridge",
"South Highpoint","South Miami Heights","South Miami","South Palm Beach","South Pasadena","South Patrick Shores","South Sarasota","South Venice","Southchase","Southeast Arcadia","Southgate","Southwest Ranches",
"Spring Hill","Spring Lake","Spring Ridge","Springfield","Springhill","Saint Augustine Beach","Saint Augustine Shores","Saint Augustine South","Saint Augustine","Saint Cloud","Saint George Island","Saint James","Saint Leo",
"Saint Lucie Village","Saint Marks","Saint Pete Beach","Saint Petersburg","Stacey Street","Starke","Steinhatchee","Stock Island","Stuart","Sugarmill Woods","Sumatra","Sun Center","Suncoast Estates",
"Sunny Isles Beach","Sunrise","Sunset","Surfside","Sweetwater","Taft","Tallahassee","Tamarac","Tamiami","Tampa","Tangelo Park","Tangerine","Tarpon Springs","Tavares","Tavernier",
"Taylor Creek","Temple Terrace","Tequesta village","The Acreage","The Crossings","The Hammocks","The Meadows","The Villages","Thonotosassa","Three Lakes","Three Oaks","Tice","Tierra Verde","Tiger Point","Tildenville",
"Timber Pines","Titusville","Town n Country","Treasure Island","Trenton","Trilby","Trinity","Tropical Park","Tyndall AFB","Umatilla","Union Park","University","University","Upper Grand Lagoon","Valparaiso",
"Valrico","Vamo","Venice Gardens","Venice","Verandah","Vernon","Vero Beach South","Vero Beach","Vero Lake Estates","Verona Walk","Viera East","Viera West","Vilano Beach","Villas","Vineyards",
"Virginia Gardens village","Wabasso Beach","Wabasso","Wacissa","Wahneta","Waldo","Wallace","Warm Mineral Springs","Warrington","Washington Park","Watergate","Watertown","Wauchula","Waukeenah","Wausau",
"Waverly","Webster","Wedgefield","Weeki Wachee Gardens","Wekiwa Springs","Welaka","Wellington village","Wesley Chapel","West Bradenton","West Canaveral Groves","West DeLand","West Lealman","West Little River",
"West Melbourne","West Miami","West Palm Beach","West Park","West Pensacola","West Perrine","West Samoset","West Vero Corridor","Westchase","Westchester","Westgate","Westlake","Weston","Westview",
"Westville","Westwood Lakes","Wewahitchka","Whiskey Creek","White","White Springs","Whitfield","Whitfield","Wildwood","Williamsburg","Williston Highlands","Williston","Willow Oak","Wilton Manors",
"Wimauma","Windermere","Winding Cypress","Windsor","Winter Beach","Winter Garden","Winter Haven","Winter Park","Winter Springs","Wiscon","Woodlawn Beach","Woodville","World Golf Village",
"Worthington Springs","Wright","Yalaha","Yankeetown","Yeehaw Junction","Yulee","Zellwood","Zephyrhills North","Zephyrhills South","Zephyrhills West","Zephyrhills","Zolfo Springs"]